name: init-action
description: 'This action is used for one time automation. It took each key from client_payload.toReplace and replace it to value'
author: carbohydrates
inputs:
  token:
    description: 'github private access token, usually secrets.GITHUB_TOKEN , needs only for pr creation'
    required: false
  event_type:
    description: 'event type that action will accept'
    required: true
    default: 'init_action'
  destroy_after_execution:
    description: 'Destroy the workflow that contains this action after successful execution'
    required: true
    default: 'true'
  create_pr:
    description: 'create pr instead of direct pushing to master'
    required: true
    default: 'false'
  author_name:
    description: 'author_name of commit'
    required: true
    default: 'initbot'
  author_email:
    description: 'git author email that will push changes'
    required: true
    default: 'initbot@example.com'
  commit_message:
    description: 'Commit message for changes'
    required: true
    default: 'init action commit'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: gray-dark
  icon: loader